use anyhow::Result;
use eframe::egui;
use std::path::{Path,PathBuf};
#[derive(Clone,Debug)] pub struct FaceMesh{pub vertices:Vec<[f32;3]>,pub faces:Vec<[usize;3]>}
#[derive(Clone,Copy,Debug,Default)] pub struct HeadPose{pub yaw:f32,pub pitch:f32,pub roll:f32,pub scale:f32}
pub fn find_mesh(dir:&Path)->Option<PathBuf>{std::fs::read_dir(dir).ok()?.flatten().map(|e|e.path()).find(|p|p.is_file()&&p.extension().and_then(|s|s.to_str())==Some("obj")&&p.file_name().and_then(|s|s.to_str()).map(|s|s.starts_with("mesh")).unwrap_or(false))}
pub fn load_obj_mesh(path:&Path)->Result<FaceMesh>{let text=std::fs::read_to_string(path)?;let mut vertices=Vec::new();let mut faces=Vec::new();for line in text.lines(){let mut it=line.split_whitespace();match it.next(){Some("v")=>vertices.push([it.next().unwrap_or("0").parse()?,it.next().unwrap_or("0").parse()?,it.next().unwrap_or("0").parse()?]),Some("f")=>{let mut idx=[0usize;3];let mut ok=true;for i in 0..3{match it.next().unwrap_or("").split('/').next().unwrap_or("").parse::<usize>(){Ok(v)if v>0=>idx[i]=v-1,_=>{ok=false;break}}}if ok&&idx.iter().all(|&i|i<vertices.len()){faces.push(idx)}},_=>{}}}if vertices.is_empty()||faces.is_empty(){anyhow::bail!("OBJ contains no triangle mesh")}Ok(FaceMesh{vertices,faces})}
pub fn estimate_head_pose(track:&crate::ar::FaceTrack)->HeadPose{if track.landmarks.len()<10{return HeadPose::default()}let p=|i|track.landmarks.get(i).copied().unwrap_or((0.5,0.5,0.0));let l=p(33);let r=p(263);let n=p(1);let m=p(13);let yaw=((n.0-0.5)*2.0).clamp(-1.0,1.0);let roll=(r.1-l.1).atan2(r.0-l.0);let ey=(l.1+r.1)*0.5;let pitch=((m.1-n.1)-(ey-n.1)).clamp(-0.8,0.8);HeadPose{yaw:yaw*0.9,pitch:pitch*0.8,roll:-roll,scale:track.bbox.2.max(1e-3).sqrt()}}
pub fn draw_wireframe(p:&egui::Painter,r:egui::Rect,m:&FaceMesh,pose:HeadPose){if m.vertices.is_empty(){return}let mut min=[f32::MAX;3];let mut max=[f32::MIN;3];for v in &m.vertices{for k in 0..3{min[k]=min[k].min(v[k]);max[k]=max[k].max(v[k]);}}let c=[(min[0]+max[0])*0.5,(min[1]+max[1])*0.5,(min[2]+max[2])*0.5];let s=0.88/(max[0]-min[0]).max(max[1]-min[1]).max(1e-4);let mut q=Vec::with_capacity(m.vertices.len());for v in &m.vertices{let(mut x,mut y,mut z)=((v[0]-c[0])*s,(v[1]-c[1])*s,(v[2]-c[2])*s);let(sy,cy)=pose.yaw.sin_cos();let(sp,cp)=pose.pitch.sin_cos();let(sr,cr)=pose.roll.sin_cos();let x1=cy*x+sy*z;let z1=-sy*x+cy*z;let y1=cp*y-sp*z1;let z2=sp*y+cp*z1;x=cr*x1-sr*y1;y=sr*x1+cr*y1;z=z2;let d=1.0/(1.0+z*0.35);q.push(egui::pos2(r.center().x+x*r.width()*0.5*d,r.center().y-y*r.height()*0.5*d));}let st=egui::Stroke::new(0.7_f32,egui::Color32::LIGHT_GREEN);for f in &m.faces{p.line_segment([q[f[0]],q[f[1]]],st);p.line_segment([q[f[1]],q[f[2]]],st);p.line_segment([q[f[2]],q[f[0]]],st);}}
